# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCustomTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCustomTableView
pod 'SpreadsheetView'
  target 'MyCustomTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCustomTableViewUITests' do
    # Pods for testing
pod 'SpreadsheetView'
  end

end
